### PR TITLE
Fix #126: GitHub Authentication is b0rked.

### LINKED ISSUE #126: GitHub Authentication is b0rked
Cannot log in with GitHub at all. We have a number of real users using GitHub as their authentication provider, so we need to get this fixed ASAP.

**This is broken on production.**

### PR DESCRIPTION
**Pull request by alastairs**
On 24 April, GitHub made a change making the User Agent mandatory in API requests. This change adds that header to our one API request, and includes a small amount of refactoring to accommodate the change more easily (switching from WebRequest to WebClient).

### CODE REVIEW

File: DDDEastAnglia/App_Code/GitHubOAuthClient.cs [hunk 1]
```diff
@@ -84,13 +84,18 @@ protected override Uri GetServiceLoginUrl(Uri returnUrl)
...
+            var uriBuilder = new UriBuilder(_userEndpoint);
+            uriBuilder.AppendQueryArgument("access_token", accessToken);
 
-            using (var response = request.GetResponse())
-            using (var responseStream = response.GetResponseStream())
-            using (var streamReader = new StreamReader(responseStream))
+            using (var webClient = new WebClient())
             {
-                return System.Web.Helpers.Json.Decode<Dictionary<string, string>>(streamReader.ReadToEnd());
+                webClient.Headers.Add(HttpRequestHeader.UserAgent, "DDD East Anglia (www.dddeastanglia.com) .NET 4.0 WebClient");
```
Comment (alastairs) [inline DDDEastAnglia/App_Code/GitHubOAuthClient.cs:92]: This line is the actual bug fix.

**Comment by alastairs** [comment]
When merged, please delete the branch too.

**Comment by alastairs** [comment]
(I'm still trying to work out how to test this.)
